variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
pages:
 stage: build
 tags:
 - Orange, Tangerine, Citrus
 script:
 - chcp 65001
 - 'Orange\Toolchain.Win\nuget.exe restore Orange\Orange.Win.sln'
 - 'Orange\Launcher\bin\Win\Release\Launcher.exe -c -j -b .\Orange\Orange.Win.sln'
 - echo "Orange build OK"
 - 'Orange\Toolchain.Win\nuget.exe restore Tangerine\Tangerine.Win.sln'
 - 'Orange\Launcher\bin\Win\Release\Launcher.exe -c -j -b .\Tangerine\Tangerine.Win.sln'
 - echo "Tangerine build OK"